# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e29d659e9cd5fd53d1e25ea683a7fb565ed31d333e193fb2ae9d04c311deaa9e734cc49e65a9fc40f56324e80bb1aabf1b45230e9876ae86f06609693fdf34ce

test:
  secret_key_base: afb8579406bdfaa0eb3ed9269619c7204f88f345c0dd83e10547bd7b96d373a3c0ba38b48584356a8a3d0757bdc0b56e9a1d473a037d007a9f522d4a13afbf13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
